micronaut:
  application:
    name: almaJobRunner
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/assets/**"
        paths: "classpath:views/assets"
  server:
    http-version: 2.0

netty:
  default:
    allocator:
      max-order: 3

git:
  temp-clone-dir-prefix: "alma-conf"

notification:
  active: false
  smtp-port: 587
