name: CI/TEST

on:
  push:
    branches: ["develop"]
    paths: ['src/**', 'pom.xml']
  pull_request:
    branches: ["main"]
    paths: ['src/**', 'pom.xml']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build/Test with Maven
        run: ./mvnw --batch-mode --errors --show-version --no-transfer-progress --strict-checksums clean test -Pjar

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v3
